[package]
name = "config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
keyring = "3"
agent = { path = "../agent" }
embedder = { path = "../embedder" }
llm = { path = "../llm" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
